name: Documentation

on:
  push:
    branches: [ main ]
    tags: '*'
    paths-ignore:
      - 'test/**'

jobs:
  make-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@v1.4
      with:
        version: 1.7
        arch: x64
    - name: Install dependencies
      run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    - name: Build and deploy
      env:
        DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      run: julia --project=docs/ docs/make.jl
